apiVersion : apps/v1
kind: Deployment
metadata:
  name: alya-web-autoscaling
  namespace: alaya-namespace
  labels:
    app : my-k8s-application
    env : prod
    owner: ArtemBorodenko
spec:
  replicas: 2
  selector:
    matchLabels:
      project: ala
  template:
    metadata:
      labels:
        project: ala
    spec:
      containers:
        - name : ala-web
          image: artemborodenko/alaya:latest
          ports:
            - containerPort: 8000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
  namespace: alaya-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v2
    kind: Deployment
    name: alaya-web-autoscaling
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80