apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-autoscaling
  namespace: {{ .Values.nm }}
spec:
  scaleTargetRef:
    apiVersion: apps/v2
    kind: Deployment
    name: alaya-web-autoscaling
  minReplicas: {{ .Values.min.ReplicasCount }}
  maxReplicas: {{ .Values.max.ReplicasCount }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetcputilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetmemorytilizationPercentage }}