apiVersion : apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.nm }}
  labels:
    app : {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: ala
  template:
    metadata:
      labels:
        project: ala
    spec:
      containers:
        - name : {{ .Values.containers.name }}-{{ .Release.Name }}
          image: {{ .Values.containers.image }}
          ports:
            - containerPort: 8000