apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.nm }}
  annotations:
      kubernetes.io/ingress.class: nginx
  labels:
    env: dev
    owner: ArtemBorodenko

spec:
  defaultBackend:
    service:
      name: app-pod-service
      port:
        number: {{ .Values.svc_port }}
  rules:
  - host: alaya133.com
    http:
      paths:
        - pathType: Prefix
          path: "/healthcheck"
          backend:
            service:
              name: app-pod-service
              port:
               number: 8000