# Default values for WebServer_Helm
#Container settings
containers:
  name: alaweb
  image: artemborodenko/alaya:latest
  ports: 8000


#Count of replicas
replicasCount: 2

#Service vars
svc_port: 8000
svc_target_port: 8000

#Namespace 
nm: alaya-namespace

#Horizontal scaling
autoscaling:
  minReplicas: 2
  maxReplicas: 6
  targetcpuUtilizationPercentage: 70
  targetmemoryUtilizationPercentage: 80

ingress:
  enabled: true
  hosts:
    - host: alaya.com
      paths:
        - path: /
          pathType: ImplementationSpecific